M48
; DRILL file {KiCad 7.0.2} date Wed Jan 31 20:38:25 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-31T20:38:25-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.660
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X14.61Y-204.169
X20.39Y-204.169
T2
X4.0Y-124.0
X4.066Y-206.0
X31.0Y-124.0
X31.0Y-206.0
T0
M30
